services:
  - type: web
    name: flappy-bird-multiplayer
    env: node
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
    plan: free 